# Generated by Django 6.0.1 on 2026-01-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
