# Generated by Django 6.0.1 on 2026-01-21 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_data_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='qty',
        ),
    ]
