# Generated by Django 6.0.1 on 2026-01-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_data_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='price2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
