# Generated by Django 6.0.1 on 2026-01-21 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_data_price2_data_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='price2',
        ),
        migrations.RemoveField(
            model_name='data',
            name='qty',
        ),
    ]
